/*
--
This file is automatically generated. Any manual changes to this file may be overwritten.
It includes routes and handlers by the Gleece API Routes Generator.
--
Authors: Haim Kastner & Yuval Pomerchik
Generated by: Gleece Routes Generator
Generated Date: 2025-02-06
Target Engine: Gin (https://github.com/gin-gonic/gin)
--
Usage:
Refer to the Gleece documentation for details on how to use the generated routes and handlers.
--
Repository: https://github.com/gopher-fleece/gleece
--
*/
package routes
import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/textproto"
	"regexp"
	"strings"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	RequestAuth "github.com/gopher-fleece/gleece/e2e/gin/auth"
	"github.com/gopher-fleece/gleece/runtime"
	E2EControllerImport "github.com/gopher-fleece/gleece/e2e/assets"
	Param33theBody "github.com/gopher-fleece/gleece/e2e/assets"
	Param38theBody "github.com/gopher-fleece/gleece/e2e/assets"
	Param41theBody "github.com/gopher-fleece/gleece/e2e/assets"
	Response62CustomError "github.com/gopher-fleece/gleece/e2e/assets"
	Response65CustomError "github.com/gopher-fleece/gleece/e2e/assets"
	E2EClassSecControllerImport "github.com/gopher-fleece/gleece/e2e/assets"
	CustomValidatorPkg0 "github.com/gopher-fleece/gleece/e2e/assets"
	MiddlewarePkg0 "github.com/gopher-fleece/gleece/e2e/gin/middlewares"
	MiddlewarePkg1 "github.com/gopher-fleece/gleece/e2e/gin/middlewares"
	MiddlewarePkg2 "github.com/gopher-fleece/gleece/e2e/gin/middlewares"
	MiddlewarePkg3 "github.com/gopher-fleece/gleece/e2e/gin/middlewares"
)
var validatorInstance *validator.Validate
var urlParamRegex *regexp.Regexp
type SecurityListRelation string
const (
	SecurityListRelationAnd SecurityListRelation = "AND"
)
type SecurityCheckList struct {
	Checks   []runtime.SecurityCheck
	Relation SecurityListRelation
}
func getStatusCode(controller runtime.Controller, hasReturnValue bool, err error) int {
	if controller.GetStatus() != nil {
		return int(*controller.GetStatus())
	}
	if err != nil {
		return http.StatusInternalServerError
	}
	if hasReturnValue {
		return http.StatusOK
	}
	return http.StatusNoContent
}
func bindAndValidateBody[TOutput any](ctx *gin.Context, contentType string, validation string, output **TOutput) error {
	var err error
	bodyBytes, err := io.ReadAll(ctx.Request.Body)
	if err != nil || len(bodyBytes) == 0 {
		if strings.Contains(validation, "required") {
			return fmt.Errorf("body is required but was not provided")
		}
		return nil
	}
	var deserializedOutput TOutput
	switch contentType {
	case "application/json":
		err = json.Unmarshal(bodyBytes, &deserializedOutput)
	default:
		return fmt.Errorf("content-type %s is not currently supported by the validation subsystem", contentType)
	}
	if err != nil {
		return err
	}
	if err = validatorInstance.Struct(&deserializedOutput); err != nil {
		return err
	}
	*output = &deserializedOutput
	return nil
}
func toGinUrl(url string) string {
	processedUrl := urlParamRegex.ReplaceAllString(url, ":$1")
	processedUrl = strings.ReplaceAll(processedUrl, "//", "/")
	if processedUrl == "" {
		return "/"
	}
	if !strings.HasPrefix(processedUrl, "/") {
		processedUrl = "/" + processedUrl
	}
	return processedUrl
}
func authorize(ctx *gin.Context, checksLists []SecurityCheckList) *runtime.SecurityError {
	var lastError *runtime.SecurityError
	for _, list := range checksLists {
		if list.Relation != SecurityListRelationAnd {
			panic(
				"Encountered a security list relation of type '%s' - this is unexpected and indicates a bug in Gleece itself." +
					"Please open an issue at https://github.com/gopher-fleece/gleece/issues",
			)
		}
		// Iterate over each security list
		encounteredErrorInList := false
		for _, check := range list.Checks {
			secErr := RequestAuth.GleeceRequestAuthorization(ctx, check)
			if secErr != nil {
				lastError = secErr
				encounteredErrorInList = true
				break
			}
		}
		// If no error was encountered, validation is considered successful
		// otherwise, we continue over to the next iteration whilst keeping track of the last error
		if !encounteredErrorInList {
			return nil
		}
	}
	// If we got here it means authentication has failed
	return lastError
}
func handleAuthorizationError(ctx *gin.Context, authErr *runtime.SecurityError, operationId string) {
	statusCode := int(authErr.StatusCode)
	if authErr.CustomError != nil {
		// For now, we support JSON only
		ctx.JSON(statusCode, authErr.CustomError.Payload)
		return
	}
	stdError := runtime.Rfc7807Error{
		Type:     http.StatusText(statusCode),
		Detail:   authErr.Message,
		Status:   statusCode,
		Instance: "/gleece/authorization/error/" + operationId,
	}
	ctx.JSON(statusCode, stdError)
}
func wrapValidatorError(validatorErr error, operationId string, fieldName string) runtime.Rfc7807Error {
	return runtime.Rfc7807Error{
		Type: http.StatusText(http.StatusUnprocessableEntity),
		Detail: fmt.Sprintf(
			"A request was made to operation '%s' but parameter '%s' did not pass validation - %s",
			operationId,
			fieldName,
			runtime.ExtractValidationErrorMessage(validatorErr, &fieldName),
		),
		Status:   http.StatusUnprocessableEntity,
		Instance: fmt.Sprintf("/gleece/validation/error/%s", operationId),
	}
}
func RegisterRoutes(engine *gin.Engine) {
	validatorInstance = validator.New()
	urlParamRegex = regexp.MustCompile(`\{([\w\d-_]+)\}`)
	validatorInstance.RegisterValidation("validate_starts_with_letter", func(fl validator.FieldLevel) bool {
		return CustomValidatorPkg0.ValidateStartsWithLetter(fl)
	})
	// E2EController
	engine.GET(toGinUrl("/e2e/simple-get"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGet")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGet()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGet'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGet",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-empty-string"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetEmptyString")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGetEmptyString()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetEmptyString'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetEmptyString",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-ptr-string"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetPtrString")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGetPtrString()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetPtrString'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetPtrString",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-null-string"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetNullString")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGetNullString()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetNullString'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetNullString",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-object"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetObject")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGetObject()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetObject'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetObject",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-object-ptr"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetObjectPtr")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGetObjectPtr()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetObjectPtr'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetObjectPtr",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-object-null"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetObjectNull")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.SimpleGetObjectNull()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetObjectNull'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetObjectNull",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/simple-get-empty"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "SimpleGetEmpty")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var queryParamRawPtr *string = nil
		queryParamRaw, isqueryParamExists := ctx.GetQuery("queryParam")
		if isqueryParamExists {
			queryParam := queryParamRaw
			queryParamRawPtr = &queryParam
		}
		if validatorErr := validatorInstance.Var(queryParamRawPtr, "required"); validatorErr != nil {
			fieldName := "queryParam"
			validationError := wrapValidatorError(validatorErr, "SimpleGetEmpty", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.SimpleGetEmpty(*queryParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'SimpleGetEmpty'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/SimpleGetEmpty",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/get-with-all-params/{pathParam}"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "GetWithAllParams")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var queryParamRawPtr *string = nil
		queryParamRaw, isqueryParamExists := ctx.GetQuery("queryParam")
		if isqueryParamExists {
			queryParam := queryParamRaw
			queryParamRawPtr = &queryParam
		}
		if validatorErr := validatorInstance.Var(queryParamRawPtr, "required"); validatorErr != nil {
			fieldName := "queryParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParams", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var pathParamRawPtr *string = nil
		pathParamRaw, ispathParamExists := ctx.Params.Get("pathParam")
		if ispathParamExists {
			pathParam := pathParamRaw
			pathParamRawPtr = &pathParam
		}
		if validatorErr := validatorInstance.Var(pathParamRawPtr, "required"); validatorErr != nil {
			fieldName := "pathParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParams", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("headerParam")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("headerParam")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParams", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.GetWithAllParams(*queryParamRawPtr, *pathParamRawPtr, *headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'GetWithAllParams'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/GetWithAllParams",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/get-with-all-params-ptr/{pathParam}"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "GetWithAllParamsPtr")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var queryParamRawPtr *string = nil
		queryParamRaw, isqueryParamExists := ctx.GetQuery("queryParam")
		if isqueryParamExists {
			queryParam := queryParamRaw
			queryParamRawPtr = &queryParam
		}
		var pathParamRawPtr *string = nil
		pathParamRaw, ispathParamExists := ctx.Params.Get("pathParam")
		if ispathParamExists {
			pathParam := pathParamRaw
			pathParamRawPtr = &pathParam
		}
		if validatorErr := validatorInstance.Var(pathParamRawPtr, "required"); validatorErr != nil {
			fieldName := "pathParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParamsPtr", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("headerParam")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("headerParam")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.GetWithAllParamsPtr(queryParamRawPtr, pathParamRawPtr, headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'GetWithAllParamsPtr'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/GetWithAllParamsPtr",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/get-with-all-params-required-ptr/{pathParam}"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "GetWithAllParamsRequiredPtr")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var queryParamRawPtr *string = nil
		queryParamRaw, isqueryParamExists := ctx.GetQuery("queryParam")
		if isqueryParamExists {
			queryParam := queryParamRaw
			queryParamRawPtr = &queryParam
		}
		if validatorErr := validatorInstance.Var(queryParamRawPtr, "required"); validatorErr != nil {
			fieldName := "queryParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParamsRequiredPtr", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var pathParamRawPtr *string = nil
		pathParamRaw, ispathParamExists := ctx.Params.Get("pathParam")
		if ispathParamExists {
			pathParam := pathParamRaw
			pathParamRawPtr = &pathParam
		}
		if validatorErr := validatorInstance.Var(pathParamRawPtr, "required"); validatorErr != nil {
			fieldName := "pathParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParamsRequiredPtr", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("headerParam")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("headerParam")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "GetWithAllParamsRequiredPtr", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.GetWithAllParamsRequiredPtr(queryParamRawPtr, pathParamRawPtr, headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'GetWithAllParamsRequiredPtr'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/GetWithAllParamsRequiredPtr",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.POST(toGinUrl("/e2e/post-with-all-params-body"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "PostWithAllParamsWithBody")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var conversionErr error
		var queryParamRawPtr *string = nil
		queryParamRaw, isqueryParamExists := ctx.GetQuery("queryParam")
		if isqueryParamExists {
			queryParam := queryParamRaw
			queryParamRawPtr = &queryParam
		}
		if validatorErr := validatorInstance.Var(queryParamRawPtr, "required"); validatorErr != nil {
			fieldName := "queryParam"
			validationError := wrapValidatorError(validatorErr, "PostWithAllParamsWithBody", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("headerParam")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("headerParam")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "PostWithAllParamsWithBody", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		var theBodyRawPtr *Param33theBody.BodyInfo = nil
		conversionErr = bindAndValidateBody(ctx, "application/json", "required", &theBodyRawPtr)
		if conversionErr != nil {
			validationError := runtime.Rfc7807Error{
				Type: http.StatusText(http.StatusUnprocessableEntity),
				Detail: fmt.Sprintf(
					"A request was made to operation 'PostWithAllParamsWithBody' but body parameter '%s' did not pass validation of '%s' - %s",
					"theBody",
					"BodyInfo",
					runtime.ExtractValidationErrorMessage(conversionErr, nil),
				),
				Status:   http.StatusUnprocessableEntity,
				Instance: "/gleece/validation/error/PostWithAllParamsWithBody",
			}
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.PostWithAllParamsWithBody(*queryParamRawPtr, *headerParamRawPtr, *theBodyRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'PostWithAllParamsWithBody'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/PostWithAllParamsWithBody",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.POST(toGinUrl("/e2e/post-with-all-params-body-ptr"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "PostWithAllParamsWithBodyPtr")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var conversionErr error
		var queryParamRawPtr *string = nil
		queryParamRaw, isqueryParamExists := ctx.GetQuery("queryParam")
		if isqueryParamExists {
			queryParam := queryParamRaw
			queryParamRawPtr = &queryParam
		}
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("headerParam")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("headerParam")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		var theBodyRawPtr *Param38theBody.BodyInfo = nil
		conversionErr = bindAndValidateBody(ctx, "application/json", "", &theBodyRawPtr)
		if conversionErr != nil {
			validationError := runtime.Rfc7807Error{
				Type: http.StatusText(http.StatusUnprocessableEntity),
				Detail: fmt.Sprintf(
					"A request was made to operation 'PostWithAllParamsWithBodyPtr' but body parameter '%s' did not pass validation of '%s' - %s",
					"theBody",
					"BodyInfo",
					runtime.ExtractValidationErrorMessage(conversionErr, nil),
				),
				Status:   http.StatusUnprocessableEntity,
				Instance: "/gleece/validation/error/PostWithAllParamsWithBodyPtr",
			}
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.PostWithAllParamsWithBodyPtr(queryParamRawPtr, headerParamRawPtr, theBodyRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'PostWithAllParamsWithBodyPtr'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/PostWithAllParamsWithBodyPtr",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.POST(toGinUrl("/e2e/post-with-all-params-body-required-ptr"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "PostWithAllParamsWithBodyRequiredPtr")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var conversionErr error
		var theBodyRawPtr *Param41theBody.BodyInfo = nil
		conversionErr = bindAndValidateBody(ctx, "application/json", "required", &theBodyRawPtr)
		if conversionErr != nil {
			validationError := runtime.Rfc7807Error{
				Type: http.StatusText(http.StatusUnprocessableEntity),
				Detail: fmt.Sprintf(
					"A request was made to operation 'PostWithAllParamsWithBodyRequiredPtr' but body parameter '%s' did not pass validation of '%s' - %s",
					"theBody",
					"BodyInfo",
					runtime.ExtractValidationErrorMessage(conversionErr, nil),
				),
				Status:   http.StatusUnprocessableEntity,
				Instance: "/gleece/validation/error/PostWithAllParamsWithBodyRequiredPtr",
			}
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.PostWithAllParamsWithBodyRequiredPtr(theBodyRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'PostWithAllParamsWithBodyRequiredPtr'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/PostWithAllParamsWithBodyRequiredPtr",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/get-header-start-with-letter"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "GetHeaderStartWithLetter")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("headerParam")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("headerParam")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required,validate_starts_with_letter"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "GetHeaderStartWithLetter", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.GetHeaderStartWithLetter(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'GetHeaderStartWithLetter'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/GetHeaderStartWithLetter",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/with-default-config-security"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "WithDefaultConfigSecurity")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("x-test-scopes")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("x-test-scopes")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "WithDefaultConfigSecurity", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.WithDefaultConfigSecurity(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'WithDefaultConfigSecurity'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/WithDefaultConfigSecurity",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/with-one-security"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName",
							Scopes: []string{
								"other",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "WithOneSecurity")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("x-test-scopes")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("x-test-scopes")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "WithOneSecurity", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.WithOneSecurity(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'WithOneSecurity'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/WithOneSecurity",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/with-two-security"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName",
							Scopes: []string{
								"other",
							},
						},
					},
				},
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"write",
								"read",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "WithTwoSecurity")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("x-test-scopes")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("x-test-scopes")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "WithTwoSecurity", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.WithTwoSecurity(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'WithTwoSecurity'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/WithTwoSecurity",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/with-two-security-same-method"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName",
							Scopes: []string{
								"other",
							},
						},
					},
				},
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName",
							Scopes: []string{
								"write",
								"read",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "WithTwoSecuritySameMethod")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("x-test-scopes")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("x-test-scopes")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "WithTwoSecuritySameMethod", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.WithTwoSecuritySameMethod(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'WithTwoSecuritySameMethod'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/WithTwoSecuritySameMethod",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/default-error"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "DefaultError")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.DefaultError()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'DefaultError'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/DefaultError",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/default-error-with-payload"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "DefaultErrorWithPayload")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.DefaultErrorWithPayload()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'DefaultErrorWithPayload'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/DefaultErrorWithPayload",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/custom-error"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "CustomError")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.CustomError()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		emptyErr := Response62CustomError.CustomError{}
		if opError == emptyErr {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != emptyErr {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			ctx.JSON(statusCode, opError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/custom-error-ptr"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "CustomPtrError")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.CustomPtrError()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			ctx.JSON(statusCode, opError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/503-error-code"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "Error503")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.Error503()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'Error503'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/Error503",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/custom-error-503"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "CustomError503")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.CustomError503()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		emptyErr := Response65CustomError.CustomError{}
		if opError == emptyErr {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != emptyErr {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			ctx.JSON(statusCode, opError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/context-access"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "ContextAccess")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.ContextAccess()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'ContextAccess'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/ContextAccess",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.GET(toGinUrl("/e2e/http-method"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "Get")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.Get()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'Get'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/Get",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.POST(toGinUrl("/e2e/http-method"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "Post")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.Post()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'Post'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/Post",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.PUT(toGinUrl("/e2e/http-method"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "Put")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.Put()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'Put'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/Put",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.DELETE(toGinUrl("/e2e/http-method"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "Delete")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.Delete()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'Delete'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/Delete",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	engine.PATCH(toGinUrl("/e2e/http-method"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName2",
							Scopes: []string{
								"config",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "Patch")
			return
		}
		controller := E2EControllerImport.E2EController{}
		controller.InitController(ctx)
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		opError := controller.Patch()
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, false, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'Patch'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/Patch",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.Header("Content-Type", "application/json")
		ctx.Status(statusCode)
	})
	// E2EClassSecController
	engine.GET(toGinUrl("/e2e/with-default-class-security"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName",
							Scopes: []string{
								"class",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "WithDefaultClassSecurity")
			return
		}
		controller := E2EClassSecControllerImport.E2EClassSecController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("x-test-scopes")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("x-test-scopes")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "WithDefaultClassSecurity", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.WithDefaultClassSecurity(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'WithDefaultClassSecurity'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/WithDefaultClassSecurity",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
	engine.GET(toGinUrl("/e2e/with-default-override-class-security"), func(ctx *gin.Context) {
		authErr := authorize(
			ctx,
			[]SecurityCheckList{
				{
					Relation: SecurityListRelationAnd,
					Checks: []runtime.SecurityCheck{
						{
							SchemaName: "securitySchemaName",
							Scopes: []string{
								"method",
							},
						},
					},
				},
			},
		)
		if authErr != nil {
			handleAuthorizationError(ctx, authErr, "WithOverrideClassSecurity")
			return
		}
		controller := E2EClassSecControllerImport.E2EClassSecController{}
		controller.InitController(ctx)
		var headerParamRawPtr *string = nil
		headerParamRaw := ctx.GetHeader("x-test-scopes")
		_, isheaderParamExists := ctx.Request.Header[textproto.CanonicalMIMEHeaderKey("x-test-scopes")]
		if isheaderParamExists {
			headerParam := headerParamRaw
			headerParamRawPtr = &headerParam
		}
		if validatorErr := validatorInstance.Var(headerParamRawPtr, "required"); validatorErr != nil {
			fieldName := "headerParam"
			validationError := wrapValidatorError(validatorErr, "WithOverrideClassSecurity", fieldName)
			ctx.JSON(http.StatusUnprocessableEntity, validationError)
			return
		}
		if continueOperation := MiddlewarePkg0.MiddlewareBeforeOperation(ctx); continueOperation == false {
			return
		}
		value, opError := controller.WithOverrideClassSecurity(*headerParamRawPtr)
		for key, value := range controller.GetHeaders() {
			ctx.Header(key, value)
		}
		ctx.Header("x-inject", "true")
		statusCode := getStatusCode(&controller, true, opError)
		if opError == nil {
			if continueOperation := MiddlewarePkg1.MiddlewareAfterOperationSuccess(ctx); continueOperation == false {
				return
			}
		}
		if opError != nil {
			if continueOperation := MiddlewarePkg2.MiddlewareOnError(ctx, opError); continueOperation == false {
				return
			}
			if continueOperation := MiddlewarePkg3.MiddlewareOnError2(ctx, opError); continueOperation == false {
				return
			}
			stdError := runtime.Rfc7807Error{
				Type:       http.StatusText(statusCode),
				Detail:     "Encountered an error during operation 'WithOverrideClassSecurity'",
				Status:     statusCode,
				Instance:   "/gleece/controller/error/WithOverrideClassSecurity",
				Extensions: map[string]string{"error": opError.Error()},
			}
			ctx.JSON(statusCode, stdError)
			return
		}
		ctx.JSON(statusCode, value)
	})
}
